[package]
name = "rustlrn"
version = "0.2.0"
edition = "2021"

[dependencies]
colored = "2.0"
clap = { version = "4.0", features = ["derive"] }
tempfile = "3.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
anyhow = "1.0"
include_dir = "0.7"
serde_yaml = "0.9"
terminal_size = "0.3"

[dev-dependencies]
tempfile = "3.0"
